config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  
  root to: 'homes#top'
  get 'home/about' => "homes#about", as: "home"
  resources :books, only: [:index,:create,:show,:edit,:destroy,:update,:destroy]
  resources :users, only: [:show,:index,:edit,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body,  presence: true
  validates :body, length: { maximum: 200 }

    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books , dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,presence: true
  validates :name,length: {minimum:2}
  validates :name,length: {maximum:20}
  validates :name,uniqueness: true
  validates :introduction,length: {maximum:50}
  
  

  has_one_attached :profile_image
  
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end


  def after_sign_out_path_for(resource)
    root_path
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) # 注目
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end
  
  def index
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new
  end
  
  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    if book.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(book.id)
    else
      @user = User.find(current_user.id)
      @books = Book.all
      @book = book
      render :index
    end
  end
  
  def show
    @aBook = Book.find(params[:id])
    @book = Book.new
    @user = @aBook.user
    
  end  
  
  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      redirect_to books_path
    end
    
  end
  
  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(book.id)
    else
      @book = book
      render :edit
    end
  end
  
  def destroy
    flash[:notice] = "Book was successfully created."
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
    
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title,:body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
 
  end
  
  def edit
    @user = User.find(params[:id])
     if current_user.id != @user.id
      redirect_to user_path(current_user.id)
     end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録ができました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user.id)
    else
      @user = user
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>New book</h2>
  <%= form_with model:@book ,url:books_path do |f|%>
    <div class="form-group">
      Title</br>
      <%= f.text_field :title,class:"form-control"%>
    </div>
    <div class="form-group">
      Opinion</br>
      <%= f.text_area :body,class:"form-control"%>
    </div>
    <%= f.submit"Create Book",class:"btn btn-success"%>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div class="error_explanation">
          <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end%>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@book do |f|%>
      <div class="form-group">
      Title</br>
      <%= f.text_field :title,class:"form-control"%>
      </div>
      <div class="form-group">
      Opinion</br>
      <%= f.text_area :body,class:"form-control"%>
      </div>
      <%= f.submit"Update Book",class:"btn btn-success"%>
      <% end %>
      <div class="mt-3 mb-6">
        <%= link_to "Show ",book_path(params[:id]) %>|
        <%= link_to " Back",books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div>
    <p><%= flash[:notice] %></p>
     <% if @book.errors.any? %>
      <div class="error_explanation">
        <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end%>
        </ul>
      </div>
    <% end %>
</div>
<div class="container">
    <div class="row">
        <%= render 'users/userinfo', user: current_user %>
        <%= render 'books/new',book: @book%>
        <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th></th>
                    </tr>
                </thead>
                <% @books.each do |b|%>
                <tbody>
                    <th>
                        <%= link_to user_path(b.user.id) do %>
                        <%= image_tag b.user.get_profile_image(100,100) %>
                        <% end %>
                    </th>
                    <th><%= link_to b.title,book_path(b.id)%></th>
                    <th><%= b.body %></th>
                </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div>
    <p><%= flash[:notice] %></p>
</div>
<div class="container">
    <div class="row mt-3">
        <%= render 'users/userinfo', user: @user %>
        <%= render 'new', book: @book %>
        <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table">
                
                <tbody>
                    <tr>
                        <td>
                            <%= image_tag @user.get_profile_image(100,100) %></br>
                            <%= link_to @user.name,user_path(@user.id) %>
                        </td>
                        <td><%= link_to @aBook.title ,book_path(@aBook.id)%></td>
                        <td><%= @aBook.body %></td>
                        <% if current_user.id == @user.id %>
                            <td><%= link_to "Edit",edit_book_path(@aBook.id),class:"btn btn-success btn-sm" %></td>
                            <td><%= link_to "Destroy",book_path(@aBook.id),method: :delete, data: {confirm: "本当に消しますか？"},class:"btn btn-sm btn-danger" %></td>
                        <% end %>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto my-3">
      <h1>Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div>
    <p><%= flash[:notice] %></p>
    <p><%= flash[:alert] %></p>
</div>
<div class="container">
    <dic class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!!</h1>
            <p>In<i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
            <p>
            you can share and exchange your opinions , inpressions , and emotions
            </p>
            <p>
            about various books!
            </p>
            <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
            <%= link_to "Log in",new_user_session_path,class:"btn btn-info btn-sm btn-block mb-3"%>
            <%= link_to "Sign up",new_user_registration_path,class:"btn btn-success btn-sm btn-block mb-3"%>
            </div>
            </div>
        </div>
    </dic>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/2a8b1dc557.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand " href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item text-white mx-2">
                <%= link_to user_path(current_user.id) ,class: "text-white" do%>
                <i class="fa-solid fa-home" style="color: #ffffff;"></i>
                Home
                <% end %>
              </li>
              <li class="nav-item text-white mx-2">
                <%= link_to users_path, class: 'text-white' do%>
                <i class="fa-solid fa-users" style="color: #ffffff;"></i>
                Users
                <% end %>
              </li>
              <li class="nav-item text-white mx-2">
                <%= link_to books_path,class: 'text-white' do%>
                <i class="fa-solid fa-book-open" style="color: #fafcff;"></i>
                Books
                <% end %>
              </li>
              <li class="nav-item text-white mx-2">
                <%= link_to destroy_user_session_path, method: :delete,class: 'text-white' do%>
                <i class="fa-solid fa-sign-out-alt" style="color: #ffffff;"></i>
                Log out
                <% end %>
              </li>

            <% else %>
            <li class="nav-item text-white mx-2">
                <%= link_to root_path ,class: "text-white" do%>
                  <i class="fa-solid fa-home" style="color: #ffffff;"></i>
                  Home
                <% end %>
            </li>
            <li class="nav-item text-white mx-2">
              <%= link_to home_path ,class: 'text-white' do%>
                <i class="fa-solid fa-link" style="color: #ffffff;"></i>
                About
              <% end %>
            </li>
            <li class="nav-item text-white mx-2">
              <%= link_to new_user_registration_path ,class: 'text-white' do%>
              <i class="fa-solid fa-user-plus" style="color: #ffffff;"></i>
              Sign up
              <% end %>
            </li>
            <li class="nav-item text-white mx-2">
              <%= link_to  new_user_session_path ,class: 'text-white' do%>
              <i class="fa-solid fa-sign-in-alt" style="color: #ffffff;"></i>
              Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
     </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_userinfo.html.erb
<div class="col-md-3">
            <h2>User Info</h2>
            <table class="table">
                <tbody>
                <%= image_tag user.get_profile_image(100,100) %>        
                    <tr>
                        <th>Name</th>
                        <th><%= user.name %></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= user.introduction %></th>
                    </tr>
                </tbody>
            </table>
            <div class="row">
                <%= link_to edit_user_path(user.id),class:"btn btn-outline-secondary btn-block" do%>
                <i class="fa-solid fa-user-cog" style="color: #818892;"></i>
                <% end %>
            </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User Info</h1>
      <% if @user.errors.any? %>
        <div class="error_explanation">
          <h3><%= @user.errors.count %> errors prohibited this book from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end%>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@user do |f|%>
      <div class="form-group">
      Name</br>
      <%= f.text_field :name,class:"form-control"%>
      </div>
      <div class="form-group">
        Image</br>
        <%= f.file_field :profile_image, accept: "image/*" %>
      </div>
      <div class="form-group">
      introduction</br>
      <%= f.text_area :introduction,class:"form-control"%>
      </div>
      <%= f.submit"Update User",class:"btn btn-secondary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div>
    <p><%= flash[:notice] %></p>
</div>
<div class="container">
    <div class="row">
     <%= render 'userinfo', user: current_user %>
     <%= render 'books/new', book: @book %>
        <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>name</th>
                        <th></th>
                    </tr>
                </thead>
                <% @users.each do |user|%>
                <tbody>
                    <td>
                        <%= link_to user_path(user.id) do %>
                        <%= image_tag user.get_profile_image(100,100) %>
                        <% end %>
                    </td>
                    <td><%= user.name %></td>
                    <td><%= link_to "Show",user_path(user.id) %></td>
                </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div>
    <p><%= flash[:notice] %></p>
    <p><%= flash[:alert] %></p>
</div>
<div class="container">
    <div class="row ">
        <%= render 'userinfo', user: @user %>
        <%= render 'books/new', book: @book%>
        <div class="col-md-8 offset-md-1 mx-auto">
            <h2>Books</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th></th>
                    </tr>
                </thead>
                <% @books.each do |book| %>
                <tbody>
                    <tr>
                      <td>
                          <%= link_to user_path(@user.id) do%>
                          <%= image_tag @user.get_profile_image(100,100) %>
                          <% end %>
                      </td>
                      <td><%= link_to book.title ,book_path(book.id)%></td>
                      <td><%= book.body %></td>
                    </tr>
                </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>